"""Adicionando email_fornecedor à tabela Produto

Revision ID: 418cca9ec2af
Revises: 4074e362103e
Create Date: 2024-11-10 18:24:07.491412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418cca9ec2af'
down_revision = '4074e362103e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_fornecedor', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('email_fornecedor')

    # ### end Alembic commands ###
